# Generated by Django 3.2 on 2021-07-09 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0002_student_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
    ]
