# Generated by Django 3.2 on 2021-07-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0004_auto_20210709_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('contact', models.URLField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='cv',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_no',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='qualification',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
